### ISSUE TITLE
Does not work for MPC3201

### ISSUE THREAD

**Issue by branossa** [labfruits/mcp3208#6]
There seem to be a slight problem when using 3201. Commands are sent to the circuit via the transfer() method even though it does not accept commands, garbling the output reply from it.
Changing the MPC320x::read() template to go through the execute() method mitigates the problem.
```
template <typename T>
uint16_t MCP320x<T>::read(Channel ch) const
{
//  return transfer(createCmd(ch));
  return execute(createCmd(ch));
}
```
Note: This have not been tested for other ADC's than 3201,

**Comment by labfruits** [comment]
This issue is fixed since v1.4.1. Please update to the latest release.
